### ISSUE TITLE
Use schema extension to define relationship semantics

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-related-tables#58]
In the current draft, there is no guidance on how to define the semantics of a relationship. The Schema Extension (describing the mapping table name, which is the only uniquely identifying value of the relationship) should be used for this purpose.

**Comment by bradh** [comment]
Possibly this would need changes on the Schema Extension side, since right now it is limited to feature data tables (or maybe feature and tiles, its not really consistent).

We'd need it to work for attribute tables (which presumably is just an oversight that didn't get handled when aspatial support was added) and for the mapping table. Right now, mapping tables would be a violation of REQ 104.

I recognise the need (and I have a case that would be a good fit for this). I'm still tempted to suggest that you run another activity to improve Schema instead of tying it to RTE.

**Comment by jyutzler** [comment]
Ooh, good point on R104.

**Comment by jyutzler** [comment]
Maybe this would be a better candidate for a Getting Started type guide than in the standard.

**Comment by jyutzler** [comment]
This was added to the [getting started guide](https://github.com/opengeospatial/geopackage-related-tables/wiki/Getting-Started#gpkgext_relations).
